# Joint Offset Configuration for LeKiwi Robot
# This file defines the angle offsets for each joint to align the physical robot with RViz
# Offsets are in degrees and will be converted to servo ticks (4096 ticks = 360 degrees)

joint_offsets:
  # Base zero position for all servos (center position)
  zero_position_base: 2048

  # Joint-specific angle offsets in degrees
  # Positive values rotate in the positive direction
  shoulder_rotation:
    angle_offset_deg: 29.0 # (-4 + 33) degrees

  shoulder_pitch:
    angle_offset_deg: 105.0 # (96 + 9) degrees

  elbow:
    angle_offset_deg: -110.0 # (-89 - 21) degrees

  wrist_pitch:
    angle_offset_deg: -74.0 # (-58 - 16) degrees

  wrist_roll:
    angle_offset_deg: -37.0 # (-7 - 30) degrees

  gripper:
    angle_offset_deg: 0.0 # No offset for gripper
